name: Staging CI/CD
on:
  push:
    tags:
      - staging/*
env:
  # How to sync these vars with other repos?
  AWS_ACCESS_KEY_ID: ${{ secrets.PROD_GITHUB_CI_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_GITHUB_CI_AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.PROD_AWS_ACCOUNT_NUMBER }}
  AWS_REGION: us-west-2
  ROOT_DOMAIN: saturn-test.network
  PUBLIC_BUCKET: filecoin-saturn-staging
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{env.AWS_REGION}}

      - name: Build and Push Assets
        env:
          STATIC_ORIGIN: https://${{env.ROOT_DOMAIN}}
          TRUSTED_L1_ORIGIN: https://${{env.ROOT_DOMAIN}}
          UNTRUSTED_L1_ORIGIN: https://${{env.ROOT_DOMAIN}}
        run: |
          npm ci
          npm run build

          aws s3 cp dist/ s3://$PUBLIC_BUCKET --recursive \
            --cache-control "public, max-age=3600" --only-show-errors
